[workspace]
members = [
        "bft-lib",
        "librabft-v2",
        "crypto",
        "store",
        "network",
        "bft-driver",
        "mempool",
        "node"
]

[profile.release]
debug = true

[profile.bench]
debug = true
