[workspace]
members = [
        "bft-lib",
        "librabft-v2",
        "crypto",
        "store",
        "network",
        "mempool",
        "consensus",
        "node"
]

[profile.release]
debug = true

[profile.bench]
debug = true
